# Generated by Django 2.2.2 on 2019-07-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
